name: smartech_appinbox
description: Smartech is a omni channel platform that delivers everything you need to drive mobile engagement and create valuable consumer relationships on mobile. The Smartech Flutter Plugin enables your Flutter app to use all of the features.
version: 3.2.9
homepage: https://netcoresmartech.com
documentation: "https://docs.netcoresmartech.com/"
license: { :type => "Commercial", :file => "LICENSE" }
repository: https://github.com/NetcoreSolutions/Smartech-Flutter-Modular.git

environment:
  sdk: '>=2.12.0 <4.0.0'  
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.netcore.smartech_appinbox
        pluginClass: SmartechAppinboxPlugin
      ios:
        pluginClass: SmartechAppinboxPlugin
